### ISSUE TITLE
[Feature Request] Permission Checks

### ISSUE THREAD

**Issue by cmprmsd** [0xsp-SRD/MDE_Enum#1]
Well done! It would be really cool if the tool also had an option to check if the current user has write access to the folder. 

Of course this could be done manually but I saw customers with many exclusion paths. That would be tedious work. :grin:

**Comment by zux0x3a** [comment]
added with following commit https://github.com/0xsp-SRD/MDE_Enum/commit/65fcb92925f5b988ecbd4599b1c5376bf6fd6914
